---
- hosts: all
  become: yes
  tasks:
  - include_tasks: wordpress_centos.yml
    when: ansible_os_family == 'RedHat'
  - include_tasks: wordpress-lamp_ubuntu1804/playbook.yml
    when: ansible_os_family == 'Debian'
