---
- hosts: webserver
  become: yes
  gather_facts: no
  tasks:
  - name: Enable php74 and epel repositories
    shell: "amazon-linux-extras enable epel -y"

  - name: enable php7.4
    shell: "sudo amazon-linux-extras enable php7.4"

  - name: Install LAMP
    yum: name={{item}}  state=present
    with_items:
    - php-cli
    - php-pdo
    - php-fpm
    - php-json
    - php-mysqlnd

  - name: Ensure service enabled and started
    service:
      name: '{{item}}'
      state: started
      enabled: True
    with_items:
    - mariadb
    - httpd

  - name: Install php-gd,rsync
    yum:
      name: '{{item}}'
      state: present
    with_items:
    - php-gd
    - rsync

  - name: Restart httpd
    service:
      name: httpd
      state: restarted

  - name: extract wordpress
    unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /root
      remote_src: yes

  - name: rsync wordpress
    shell: rsync -avP /root/wordpress/ /var/www/html/ #tao bang modul file cua ansible
  
  - name: Set user:group
    shell: chown -R apache:apache /var/www/html/* #tao bang modul file cua ansible

  - name: Install MySQL-python
    yum:
      name: MySQL-python
      state: present

  - name: Create database wordpress
    mysql_db:
      name: wordpress
      state: present
  
  - name: Create user wordpressuser
    mysql_user:
      name: wordpressuser
      host: localhost
      password: wordpresspassword
      priv: 'wordpress.*:ALL'
      state: present

  - name: Backup file config wp
    shell: cp /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
  
  - name: Config db name
    replace:
      path: /var/www/html/wp-config.php
      regexp: 'database_name_here'
      replace: 'wordpress'
  
  - name: Config username
    replace:
      path: /var/www/html/wp-config.php
      regexp: 'username_here'
      replace: 'wordpressuser'
  
  - name: Config password
    replace:
      path: /var/www/html/wp-config.php
      regexp: 'password_here'
      replace: 'wordpresspassword'

  - name: Config version PHP
    yum: name= {{item}} state=present update_cache=true
    with_items:
      - epel-release
      - yum-utils
      - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
  
  - name: Config version PHP
    shell: sudo yum-config-manager --enable remi-php72

  - name: Config version PHP
    yum:
      name: '{{item}}'
      state: present
    with_items:
    - php
    - php-common
    - php-cli
    - php-gd
    - php-curl
    - php-mysqlnd

  - name: Restart Apache
    service:
      name: httpd
      state: restarted
