
- name: Include version-specific variables for CentOS/RHEL.
  include_vars: RedHat-7.yml
  # when: ansible_distribution == 'CentOS' or
  #       ansible_distribution == 'Red Hat Enterprise Linux' or
  #       ansible_distribution == 'RedHat'
  #       ansible_distribution == 'Amazon'

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
  when: ansible_distribution == 'Ubuntu'

- name: Define java_packages.
  set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

- name: Define java_home.
  set_fact:
    java_home: "{{ __java_home }}"
  when: java_home is not defined

# Setup/install tasks.
- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined

- name: Export JAVA_HOME
  command: echo $JAVA_HOME

- name: Check the Java version
  command: java -version
  changed_when: false
  register: java_version

- name: Display the Java version.
  debug:
    var: java_version
    verbosity: 2
